sudo: true
language: c
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.8
      - g++-5
      - gcc-5
script:
  - ./.travis.sh
matrix:
  include:
    - os: linux
      compiler: gcc
      env: "BUILD_SYSTEM=autotools"
    - os: linux
      compiler: clang
      env: "BUILD_SYSTEM=autotools"
    - os: linux
      compiler: gcc-5
      env: "BUILD_SYSTEM=cmake"
    - os: linux
      compiler: clang-3.8
      env: "BUILD_SYSTEM=cmake"
    - os: osx
      compiler: clang
      env: "BUILD_SYSTEM=cmake"
    - os: osx
      compiler: clang
      env: "BUILD_SYSTEM=autotools"
